[workspace]
members = ["gen"]
exclude = ["fuzz"]

[package]
name = "lamy"
version = "0.0.2"
edition = "2024"
license = "Apache-2.0"
authors = ["Matilde Morrone <contact@matilde.pet>"]
repository = "https://github.com/puppymati/lamy"
description = "A simple but correct yaml parsing library"
readme = "README.md"
documentation = "https://docs.rs/lamy"
include = ["src/**/*.rs", "README.md", "LICENSE"]

[dependencies]
bytes = "1.11.1"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"

[dev-dependencies]
anyhow = "1.0.102"
serde = { version = "1.0.228", features = ["derive"] }
